## Add to .hg/hgrc to enable bitbucket pushes to push to github as well.
# [hooks]  
# outgoing = hg push git+ssh://git@github.com/jmchilton/lwr.git || true
language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - REQUIREMENTS_SUFFIX=
install:
  - sudo apt-get install libxml2-dev libxslt1-dev libcurl3 python-pycurl
  - pip install -r requirements$REQUIREMENTS_SUFFIX.txt --use-mirrors || true
  - pip install -r dev-requirements$REQUIREMENTS_SUFFIX.txt --use-mirrors || true
script: nosetests
matrix:
  include:
    - python: 3.3
      env: REQUIREMENTS_SUFFIX=3
  allow_failures:
    - python: 3.3     
